## Estuardo J. Díaz García (22008995)

# Ejercicio. Notebook #7
---
**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

## Arrays en NumPy

Un **array** es una estructura de datos dentro de NumPy de un mismo tipo, organizada en forma de tabla o en una cuadrícula de distintas dimensiones.

 - **a.ndim** : Devuelve el número de **dimensiones** del array a.
 - **a.shape** : Devuelve una **tupla con las dimensiones** del array a.
 - **a.size** : Devuelve el **número de elementos** del array a.
 - **a.dtype**: Devuelve el **tipo de datos** de los elementos del array a.
 
Los arrays pueden tener de 1 a infinitas dimensiones: una dimensión (vectores), dos dimensiones (similares a las matrices), tres dimensiones (cubos), etc...

<img src=https://aprendeconalf.es/docencia/python/manual/img/arrays.png>

Fuente: https://aprendeconalf.es/

In [45]:
import numpy as np
#Veamos algunos ejemplos de arrays
ejemplo1 = np.array([100,200,300]) #este es un array de 1 dimensión, conocido también como vector

#Podemos ver las propiedades del array
print("Dimensión del array:",ejemplo1.ndim)
print("Forma del array: (filas x columnas)",ejemplo1.shape)
print("Tamaño del array:",ejemplo1.size)
print("Tipo de datos del array:",ejemplo1.dtype)
print(" ")
print(ejemplo1)
print(type(ejemplo1))
print(" ")
print("----------------")
print(" ")
ejemplo2 = np.array([[100,200,300], [400, 500, 600]])
#Podemos ver las propiedades del array
print("Dimensión del array:",ejemplo2.ndim)
print("Forma del array: (filas x columnas)",ejemplo2.shape)
print("Tamaño del array:",ejemplo2.size)
print("Tipo de datos del array:",ejemplo2.dtype)
print(" ")
print(ejemplo2)
print(type(ejemplo2))
print(" ")
print("----------------")
print(" ")
ejemplo3 = np.array([[[100,200,300], [400, 500, 600]],[[700,800,900],[1000,1100,1200]]])
#Podemos ver las propiedades del array
print("Dimensión del array:",ejemplo3.ndim)
print("Forma del array: (filas x columnas)",ejemplo3.shape)
print("Tamaño del array:",ejemplo3.size)
print("Tipo de datos del array:",ejemplo3.dtype)
print(" ")
print(ejemplo3)
print(type(ejemplo3))




Dimensión del array: 1
Forma del array: (filas x columnas) (3,)
Tamaño del array: 3
Tipo de datos del array: int32
 
[100 200 300]
<class 'numpy.ndarray'>
 
----------------
 
Dimensión del array: 2
Forma del array: (filas x columnas) (2, 3)
Tamaño del array: 6
Tipo de datos del array: int32
 
[[100 200 300]
 [400 500 600]]
<class 'numpy.ndarray'>
 
----------------
 
Dimensión del array: 3
Forma del array: (filas x columnas) (2, 2, 3)
Tamaño del array: 12
Tipo de datos del array: int32
 
[[[ 100  200  300]
  [ 400  500  600]]

 [[ 700  800  900]
  [1000 1100 1200]]]
<class 'numpy.ndarray'>


## Matrices en NumPy

Las matrices son objetos especiales de arrays con 2D. Los datos en una matriz pueden ser números, cadenas, expresiones, símbolos, etc. La matriz es una de las estructuras de datos importantes que se pueden usar en cálculos matemáticos y científicos.

Al utilizar la sentencia np.matrix este objeto adquiere ciertas propiedades que lo diferencian de un array.

In [43]:
#Vamos un ejemplo de la sentencia np.matrix
q = np.matrix([[1000, 7], [13, 45]])
print(q)
type(q)

[[1000    7]
 [  13   45]]


numpy.matrix

In [48]:
#También podemos comvertir un array en una matriz usando np.asmatrix
y = np.asmatrix(ejemplo2) #de los ejemplos del inciso anterior
y


matrix([[100, 200, 300],
        [400, 500, 600]])

In [50]:
#o una matriz la volvemos array con la sentencia np.asarray 
g = np.asarray(y)
g

array([[100, 200, 300],
       [400, 500, 600]])

## Principales diferencias:

Las matrices numpy son estrictamente 2D, mientras que las arrays (ndarrays) pueden tener múltiples dimensiones. Los objetos *matrix* son una subclase de arrays, por lo que heredan todos los atributos y métodos de ndarrays.

La principal ventaja de las matrices numpy es que proporcionan una notación conveniente para la multiplicación de matrices.

A las matrices se les puede aplicar ciertas operacione que a los arrays no, como conjugadas transpuestas (.H) e inversas (.I)
Así también el operador ** también se comporta diferente.

En conclusión, visualmente las matrices y los arrays en python son iguales, sin embargo, sus propiedades y operaciones que se pueden aplicar en ellas varían.

